### ISSUE TITLE
androidのPluginコードが除外されておりビルドできない

### ISSUE THREAD

**Issue by takumiito271** [HearableDev/Hearable#1]
# 概要
必要なAndroid用のネイティブコードがignoreされており、exampleプロジェクトのpub getに失敗する

[![Image from Gyazo](https://i.gyazo.com/0715ba8833ae2ac4a4e70dbe0629a971.png)](https://gyazo.com/0715ba8833ae2ac4a4e70dbe0629a971)

https://github.com/HearableDev/Hearable/blob/4cf4337140d438d7c246a1ceae2a30711df613e8/hearable_device_sdk_sample_plugin/.gitignore#L33C9-L33C9

**Comment by HearableDev** [comment]
hearable_device_sdk_sampleと同じ階層レベルにhearable_device_sdk_sample_pluginフォルダは存在していますか？
もし存在していなければ作成していただき、その中に関連するSDKファイルを格納して再度試してみてください。

**Comment by takumiito271** [comment]
hearable_device_sdk_sample_pluginは存在しており、SDKもダウンロードしたものをiOS、AndroidともにREADMEで指定されたディレクトリに格納済みです。

**Comment by HearableDev** [comment]
ビルドに必要なhearable_device_sdk_sample_plugin配下のデータを追加しました。再度ご確認をお願いいたします。
