### ISSUE TITLE
Windows用のSDKについて

### ISSUE THREAD

**Issue by ghost** [HearableDev/Hearable#4]
Windows用のアプリケーションを開発したいと考えています。
Windows用のSDKの公開予定はありますか？

**Comment by HearableDev** [comment]
お問い合わせありがとうございます。
Windows用SDKについては、本日時点で公開予定はございません。

**Comment by ghost** [comment]
早速のご回答ありがとうございます。
現状、公開予定はないとのこと承知いたしました。

**Comment by HearableDev** [comment]
可能な範囲で構わないのですが、ヒアラブルデバイスのどの機能を想定されているかを教えていただくことは可能でしょうか？
耳音響認証・9軸センサ・外耳孔表面温度・脈関連情報・その他

**Comment by ghost** [comment]
９軸センサ情報や一通りの生体情報を想定しています。
PC上でモニタリングやデータ解析をできればと考えています。

**Comment by HearableDev** [comment]
先日はご回答ありがとうございました。

一通りの生体情報はスマホから取得してPCに送るようなこともできなくないかとは思われますが、可能でしたら、直接PC上でモニタリングやデータ解析を行いたい理由を教えていただけると幸いです。

**Comment by ghost** [comment]
ご返信ありがとうございます。

おっしゃる通り、現在スマホから取得してPCに送る方法を検討しております。
PCで直接取得したい理由としては、これまでwindowsにて解析ソフトを開発しているためです。また、スマホ経由で取得もできると思いますが、できるだけ簡易にできるようにしたいためです。

**Comment by HearableDev** [comment]
ご回答ありがとうございます。
承知いたしました。
